% Prepare to release
release: sh -c 'python manage.py makemigrations && python manage.py migrate && PGPASSWORD=b97711ed2f8c613f57995cc9e88a90ff67a80336f3fb88240f2b8d6ae9179a2c pg_restore --verbose --clean --no-acl --no-owner -n public -h ec2-54-247-70-127.eu-west-1.compute.amazonaws.com -U dixwkzhssdzqos -d d2paa556frtt4j -p 5432 Populate_travelmate'
% Launch!
web: sh -c 'gunicorn TravelMateServer.wsgi --log-file -'
